server.port = 8285
server.servlet.context-path=/AccountManagementAPI
#server.servlet.context-path=/AccountManagementAPI/NGN

api_secret_key = SEQ1951RSEKFSDHWJKFASFEEJ3RO

#added by ankit
file.upload.location=C:\\AMS\\Speta\\imageUploads
#file.upload.location=D:\imageUploads
#file.upload.location=/usr/app/Paths/imageUploads

#added by ankit on 09-05-2023
file.upload.tier=C:\\AMS\\Speta\\TierPhotos
#file.upload.tier=D:\TierPhotos
#file.upload.tier=/usr/app/Paths/TierPhotos
#added by ankit on 09-05-2023

file.qrcode.imagepath=C:\\AMS\\Speta\\qrcode
#file.qrcode.imagepath=/usr/app/Paths/AMS/Speta/qrcode

file.dqrcode.imagepath=C:\\AMS\\Speta\\dynamic\\qrcode
#file.dqrcode.imagepath=/usr/app/Paths/AMS/Speta/dynamic/qrcode

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

server.tomcat.max-swallow-size=1000MB

#ams.server.url = http://localhost
ams.server.url = http://103.11.153.212

ams.sms.local.url = http://sms.digimiles.in/bulksms/bulksms

ams.sms.global.url = http://global.digimiles.in:8080/bulksms/bulksms

middleware_getbank_url = http://10.111.23.244:8065/montramw/banklist 

middleware_sendMoney_url = http://10.111.23.244:8065/montramw/sendmoney

middleware_nameenquiry_url = http://10.111.23.244:8065/montramw/nameinquiry 

montra_generate_totp_url = http://localhost:8100/verifyer/api/v1/generate

montra_verify_key_url = http://localhost:8100/verifyer/api/v1/verifyforkey  

#database configuration 
#database_url=jdbc:mysql://localhost:3306/account_management?useSSL=false
database_url=jdbc:mysql://localhost:3306/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
#database_url=jdbc:mysql://localhost:3303/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
#datasource.localurl=jdbc:mysql://database/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
database_username=root
#database_password=SEP@ssw0rd123
database_password=root

#Email Configuration
#email.host = email-smtp.eu-west-1.amazonaws.com


#root level debug
#logging.level.root=debug

#logging pattern for console
#logging.pattern.console=%date{ISO8601} %-5level %class{0}:%L -[%X] %msg%n

#logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n
#logging.pattern.file= %-4relative [%thread] %-5level %logger{35} - %msg%n

#logging pattern for file
#logging.pattern.file=%date{ISO8601} %-5level %class{0}:%L -[%X] %msg%n

# output file of logging
#logging.file.name=ams-application.log