mode=local

#datasource_config
#first connection

#datasource.localurl=jdbc:mysql://localhost:3306/account_management?useSSL=false
datasource.localurl=jdbc:mysql://localhost:3306/account_management_sys?useSSL=false&allowPublicKeyRetrieval=true
#datasource.localurl=jdbc:mysql://localhost:3303/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
#datasource.localurl=jdbc:mysql://database/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
datasource.localuser=root
#datasource.localpassword=SEP@ssw0rd123
datasource.localpassword=root
#datasource.localpassword=v18OyXM7q+aHJbsxpWX9nw==


#first_driver
datasource.driver_class=com.mysql.jdbc.Driver
#datasource.produrl=jdbc:mysql://localhost:3306/account_management?useSSL=false
datasource.produrl=jdbc:mysql://localhost:3306/account_management_sys?useSSL=false&allowPublicKeyRetrieval=true
#datasource.produrl=jdbc:mysql://localhost:3303/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
#datasource.localurl=jdbc:mysql://database/account_management_dev?useSSL=false&allowPublicKeyRetrieval=true
datasource.produser=root
#datasource.prodpassword=SEP@ssw0rd123
datasource.prodpassword=root
#datasource.prodpassword=v18OyXM7q+aHJbsxpWX9nw==


#hibernateconfig
#org.hibernate.dialect.SQLServer2012Dialect.class
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=none
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
hibernate.connection.pool_size=10
hibernate.connection.release_mode=after_transaction
hibernate.jdbc.batch_size=0
hibernate.connection.autotocommit=false
hibernate.cache.use_second_level_cache=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

#com.microsoft.sqlserver.jdbc.SQLServerDataSource
hikari.dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
hibernate.connection.provider_class=com.zaxxer.hikari.hibernate.HikariConnectionProvider
hikari.maximumPoolSize=10
hikari.idleTimeout=30000
hikari.connectionTimeout=30000
hikari.maxLifetime=1800000
hikari.dataSource.cachePrepStmts=true
hikari.dataSource.prepStmtCacheSize=250
hikari.dataSource.prepStmtCacheSqlLimit=2048
hikari.dataSource.useServerPrepStmts=true
hikari.connectionTestQuery=SELECT 1