server.port=8285
server.servlet.context-path=/AccountManagementAPI

ams.server.url=http://${EC2_PUBLIC_IP:localhost}

file.upload.location=/usr/app/data/imageUploads
file.upload.tier=/usr/app/data/TierPhotos
file.qrcode.imagepath=/usr/app/data/qrcode
file.dqrcode.imagepath=/usr/app/data/dynamic/qrcode

database_url=jdbc:mysql://mysql:3306/account_management_sequro?useSSL=false&allowPublicKeyRetrieval=true
database_username=root
database_password=${MYSQL_ROOT_PASSWORD}
