mode=local

datasource.localurl=jdbc:mysql://mysql:3306/account_management_sequro?useSSL=false&allowPublicKeyRetrieval=true
datasource.localuser=root
datasource.localpassword=${MYSQL_ROOT_PASSWORD}
datasource.driver_class=com.mysql.jdbc.Driver

datasource.produrl=jdbc:mysql://mysql:3306/account_management_sequro?useSSL=false&allowPublicKeyRetrieval=true
datasource.produser=root
datasource.prodpassword=${MYSQL_ROOT_PASSWORD}

hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.hbm2ddl.auto=none
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
hibernate.connection.pool_size=10
hibernate.connection.release_mode=after_transaction
hibernate.jdbc.batch_size=0
hibernate.connection.autotocommit=false
hibernate.cache.use_second_level_cache=false

hikari.dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
hibernate.connection.provider_class=com.zaxxer.hikari.hibernate.HikariConnectionProvider
hikari.maximumPoolSize=10
hikari.idleTimeout=30000
hikari.connectionTimeout=30000
hikari.maxLifetime=1800000
hikari.dataSource.cachePrepStmts=true
hikari.dataSource.prepStmtCacheSize=250
hikari.dataSource.prepStmtCacheSqlLimit=2048
hikari.dataSource.useServerPrepStmts=true
hikari.connectionTestQuery=SELECT 1
